# Configuration file for TravisCI

sudo: required
language: python
python: 3.6

env:
    global:
        - BUILD_PDF="true"
        - HTML_BUILDDIR=build/dirhtml
        - GMT_VERSION=5.4.5
        # Install location
        - TEXLIVE_INSTALL_PREFIX=${HOME}/.TinyTeX
        - CONDA_INSTALL_PREFIX=${HOME}/miniconda
        - PATH=${CONDA_INSTALL_PREFIX}/bin:${TEXLIVE_INSTALL_PREFIX}/bin/x86_64-linux:${PATH}

cache:
    pip: true
    directories:
        - ${TEXLIVE_INSTALL_PREFIX}
        - ${CONDA_INSTALL_PREFIX}

# Only build pushes to select branches and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
    only:
        - master
        # Regex to build tagged commits with version numbers
        - /\d+\.\d+(\.\d+)?(\S*)?$/

install:
    # Install SourceCodePro fonts for PDF
    - if [ "$BUILD_PDF" == "true" ]; then
        curl -sSL https://raw.githubusercontent.com/seisman/install/master/install-SourceCodePro.sh | bash;
      fi
    # Install tinytex (https://github.com/yihui/tinytex)
    - if [ ! -d "${TEXLIVE_INSTALL_PREFIX}/bin/x86_64-linux" ]; then
        wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh;
        tlmgr install ctex ms xecjk ulem zhnumber fancyhdr titlesec tabulary varwidth
                      float wrapfig parskip capt-of needspace xcolor enumitem xindy fandol;
      fi
    # Setup conda, install dependencies and install GMT
    - if [ ! -d "${CONDA_INSTALL_PREFIX}/bin" ]; then
        source ci/install-gmt-via-conda.sh;
      fi
    - if [[ $(gmt --version) == ${GMT_VERSION}* ]]; then
        exit;
      fi

script:
    # build html or/and PDF
    - if [ "$BUILD_PDF" == "true" ]; then
        make build;
      else
        make dirhtml;
      fi

deploy:
    provider: script
    script: bash ci/deploy-gh-pages.sh
    skip_cleanup: true
    on:
        branch:
            - master
            - /\d+\.\d+(\.\d+)?(\S*)?$/
